# PARA IMPORTAR TODA A BIBLIOTECA
# PARA IMPORTAR BIBLIOTECAS, USAMOS O COMANDO IMPORT + BIBLIOTECA
import tkinter # TKINTER -> BIBLIOTECA

#VARIAVEL TK RECEBEU A BIBLIOTECA
tk = tkinter



# IMPORTAR APENAS ALGUMAS FUNÇÕES

# FROM + BIBLIOTECA + IMPORT + FUNÇÕES
from math import sqrt, ceil, floor # MATH -> BIBLIOTECA DE MATEMATICA

paracima = ceil()
parabaixo = floor()






